### ISSUE TITLE
Permitir atualização de documento já enviado para o índice

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeDup#12]
Atualmente para cada atualização realizada no FI-ADMIN é criado uma nova entrada no índice DeDup.

Levar em consideração o parâmetro **ref_id** para determinar se o documento deve ser criado ou atualizado no índice DeDup.

* Obs: Para documentos que possuem títulos em mais de um idioma sera realizado uma requisição de PUT para cada ocorrência do título e o parâmetro ref_id será a concatenação do ID do FI-ADMIN mais o código de 2 letras do idioma do título. Ex. fiadmin-99999-es

**Comment by viniciusandrade** [comment]
@heitorbarbieri 
Pelos testes iniciais parece estar tudo OK, enviando o mesmo documento com mesmo ID é atualizado no índice e não criado nova ocorrência. 

Obrigado

**Comment by heitorbarbieri** [comment]
@viniciusandrade 
Havia me esquecido deste issue e em commit recente desfiz este check pois o mesmo acarreta em acréscimo de horas de processamento quando na criação de um índice full do LILACS_Sas. Precisamos reavaliar a real necessidade deste check devido ao alto custo envolvido, e conforme a decisão, retornar o check.

**Comment by viniciusandrade** [comment]
@heitorbarbieri,

OK, desde que seja garantido que ao consultar o serviço não sejam retornados múltiplos registros iguais, lembrando que o usuário pode salvar várias vezes um mesmo registro no FI-ADMIN até a sua conclusão (preenchimento, indexação, validação etc) estarei enviando os mesmos metadados para o DeDup múltiplas vezes e por isso foi adicionado o parâmetro **ref_id**.

**Comment by renatomurasaki** [comment]
@heitorbarbieri não sei se tem que voltar com o check, mas precisa ter o comportamento descrito pelo @viniciusandrade no comentario https://github.com/bireme/DeDup/issues/12#issuecomment-632720645

**Comment by heitorbarbieri** [comment]
@viniciusandrade e @renatomurasaki ,

Veficando o código, observei que na situação atual, quando se entram documentos em lote, o sistema não checa duplicidade, mas quando se utiliza o webservice, existe sim a verificação de duplicidade. Fica então assim a solução ótima, pois é a entrada em lote (cuja duplicidade dos documentos é verificada antecipadamente) que possui o problema de performance e cuja verificação está desativada. Já na entrada para o índice de documento a documento (caso do webservice) a checagem é realizada.
