### ISSUE TITLE
Permitir apagar documentos do índice DeDup

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeDup#13]
Criar método que permita apagar todos os documentos associados a um registro do FI-ADMIN.

Levar em consideração o atributo **ref_id** que pode ou não estar completo. Por exemplo, para apagar todos as entradas no índice referentes ao registro 9090 o parâmetro ref_id poderia ser informado como: **fiadmin-9090-***

**Comment by heitorbarbieri** [comment]
Feito no commit 44f9a46
