### ISSUE TITLE
Criar schema e índice de fonte

### ISSUE THREAD

**Issue by suelisuga** [bireme/DeDup#16]
Solicito criação de schema e índice de fonte para:

-Periódicos:
Campos - título do periódico, volume, ano e, se houver, os campos de ISSN e Número também.

-MNT:
Campos: Título, ano, país de publicação
Considerar também campos: edição e autor.

Obrigada

Sueli

**Comment by heitorbarbieri** [comment]
Criado. Falta a verificação se os valores dos parâmetros estão bem ajustados.

**Comment by heitorbarbieri** [comment]
Feito em commit 4b588f3
