### ISSUE TITLE
Criar schema e índice para fonte Recursos de Internet

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeDup#18]
Este índice será utilizado para auxiliar na detecção de possíveis duplicados na entrada de dados do FI-ADMIN para recursos de Internet da mesma forma como ocorre atualmente para registros bibliográficos. 

Relacionado ao issue https://github.com/bireme/fi-admin/issues/1062

**Comment by viniciusandrade** [comment]
@heitorbarbieri 

Favor criar no serviço base **LIS**, schema **LIS_Two**, campos **titulo** e **url** 

A busca será realizada principalmente pelo título do site.

**Comment by heitorbarbieri** [comment]
Feito em commit 4b588f3
