### ISSUE TITLE
Verificação de duplicados na base de Recursos de Internet (FI-ADMIN)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeDup#2]
@heitorbarbieri 

A URL da API para consumir os registros da base de Recursos de Internet e carregar no índice de verificação de duplicações é:

http://fi-admin.bvsalud.org/api/resource/

parâmetros:

format = (xml / json)
limit = quantidade de registros (0 para todos)
offset = registro inicial

**Comment by anakatiacamilo** [comment]
Campos para check de duplicação:
link;
title;
originator;

**Comment by heitorbarbieri** [comment]
Como não existem os campos de data de início e de fim que ajudam muito na determinação de duplicados, acrescentei também aos campos pedidos, o campo "abstract".

**Comment by heitorbarbieri** [comment]
Lista de registros duplicados enviada por email para @anakatiacamilo. Aguardando verificação da qualidade do resultado procuzido.
