### ISSUE TITLE
Verificação de duplicados na base de Eventos (FI-ADMIN)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeDup#3]
@heitorbarbieri 

A URL da API para consumir os registros da base de Eventos e carregar no índice de verificação de duplicações é:

http://fi-admin.bvsalud.org/api/event/

parâmetros:

format = (xml / json)
limit = quantidade de registros (0 para todos)
offset = registro inicial

**Comment by anakatiacamilo** [comment]
title;
start_date;
end_date;
city; (Não é obrigatório)
link (Não é obrigatório)

**Comment by heitorbarbieri** [comment]
Lista de registros duplicados enviada por email para @anakatiacamilo. Aguardando verificação da qualidade do resultado procuzido.
