### ISSUE TITLE
Verificar atualização do base lilacs_Sas_Source

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/DeDup#30]
@heitorbarbieri realizei alguns testes para validar a nova versão do serviço mas não estou obtendo resposta para a base **lilacs_Sas_Source** nos exemplos abaixo de registro-fonte do FI-ADMIN antigos: 

https://dedup.bireme.org/services/get/duplicates?database=lilacs_Sas_Source&schema=LILACS_Sas_Source&titulo_revista=Clin. biomed. res&volume_fasciculo=42&numero_fasciculo=3

https://dedup.bireme.org/services/get/duplicates?database=lilacs_Sas_Source&schema=LILACS_Sas_Source&titulo_revista=Rev. cient. cienc. salud&volume_fasciculo=5&numero_fasciculo=1

**Comment by heitorbarbieri** [comment]
@viniciusandrade faltaram parâmetros ISSN e data_iso nas suas chamadas. Veja as chamadas corretas:

https://dedup.bireme.org/services/get/duplicates?database=lilacs_Sas_Source&schema=LILACS_Sas_Source&titulo_revista=Clin.%20biomed.%20res&ISSN=2357-9730&volume_fasciculo=42&numero_fasciculo=3&data_iso=2022

https://dedup.bireme.org/services/get/duplicates?database=lilacs_Sas_Source&schema=LILACS_Sas_Source&titulo_revista=Rev.%20cient.%20cienc.%20salud&ISSN=2664-2891&volume_fasciculo=5&numero_fasciculo=1&data_iso=2023

**Comment by viniciusandrade** [comment]
@heitorbarbieri conforme verificamos favor adicionar novamente uma opção de busca usando título da revista, volume e número.

**Comment by viniciusandrade** [comment]
Ajuste realizado para utilizar na consulta o schema **LILACS_Sas_Source_Three**, tudo OK agora. 

Obrigado
