### ISSUE TITLE
Registros duplicados, mas com tipo de publicação diferente

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DeDup#5]
Conversar sobre os registros duplicados que foram cadastrados com tipos de publicação diferentes.

Exemplo: documentos de "Cadernos de atenção básica" foram cadastrados com Coleção em uma BVS e Monografia em Serie em outra BVS.

**Comment by heitorbarbieri** [comment]
@anakatiacamilo 
Para fazermos isto, é necessário que se crie um índice contendo os elementos em comum aos dois tipos de publicação e daí se realize o check de duplicados normalmente.
